### ISSUE TITLE
can't build on rustc 1.20.0-nightly

### ISSUE THREAD

**Issue by bbigras** [purpliminal/rust-dotenv#69]
```
error[E0046]: not all trait items implemented, missing: `extract_backtrace`
  --> C:\Users\bbigras\.cargo\registry\src\github.com-1ecc6299db9ec823\dotenv-0.10.1\src\lib.rs:22:17
   |
22 | #[derive(Debug, error_chain)]
   |                 ^^^^^^^^^^^ missing `extract_backtrace` in implementation
   |
   = note: `extract_backtrace` from trait: `fn(&std::error::Error + std::marker::Send + 'static) -> std::option::Option<
std::sync::Arc<error_chain::Backtrace>>`

error: aborting due to previous error

error: Could not compile `dotenv`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

Default host: x86_64-pc-windows-msvc

nightly-x86_64-pc-windows-msvc (default)
rustc 1.20.0-nightly (afe145d22 2017-07-23)

**Comment by bbigras** [comment]
I think it happens when one of by dependencies use `error-chain` with the `backtrace` feature.

**Comment by yutasth** [comment]
I found that the error happens when compiling Iron or Rocket with Diesel and R2D2.
The error happens when compiling _without_ writing below in Cargo.toml expressly:
```
[dependencies]
dotenv = "0.10.*"
```

Env:
 Rustc 1.19.0 stable / 1.21.0-nightly

**Comment by r-arias** [comment]
> The error happens when compiling *without* writing below in Cargo.toml expressly:

this workaround worked for me! thanks a lot!

**Comment by yyolf117** [comment]
what does this mean "The error happens when compiling without writing below in Cargo.toml expressly:"?

**Comment by adwhit** [comment]
It means - add that line and the error goes away. (please be civil)

**Comment by yyolf117** [comment]
fucking shit still.

**Comment by Boscop** [comment]
Why exactly is the `.*` necessary?

This solutions doesn't work for me, I just upgraded from diesel 0.14 to 0.15 (I want to update to 1.0 in smaller steps), and it was working with diesel 0.14 but with 0.15 I get this error, why?

I think it's because of infer_schema somehow?

**Comment by Boscop** [comment]
When I run `cargo tree -p error-chain -i`, I get:
```
error-chain v0.10.0
├── cron v0.4.0
│   └── job_scheduler v1.0.4
│       └── webserver v0.1.0 (file:///D:/docs/foo/foo-server/server)
│           ├── foo-server v0.1.0 (file:///D:/docs/foo/foo-server)
│           └── scale-server v0.1.0 (file:///D:/docs/foo/foo-server/scale-server)
│               └── foo-server v0.1.0 (file:///D:/docs/foo/foo-server) (*)
├── dotenv v0.10.1
│   ├── diesel_codegen v0.15.0
│   │   └── webserver v0.1.0 (file:///D:/docs/foo/foo-server/server) (*)
│   └── foo-server v0.1.0 (file:///D:/docs/foo/foo-server) (*)
└── webserver v0.1.0 (file:///D:/docs/foo/foo-server/server) (*)
```
It compiles when I do cargo build from the workspace root (foo-server), but not when I try to build in foo-server/server, why?

Then I get:
```js
λ cargo build                                                                                                           
   Compiling dotenv v0.10.1                                                                                             
error[E0046]: not all trait items implemented, missing: `extract_backtrace`                                             
  --> C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\dotenv-0.10.1\src\lib.rs:22:17                        
   |                                                                                                                    
22 | #[derive(Debug, error_chain)]                                                                                      
   |                 ^^^^^^^^^^^ missing `extract_backtrace` in implementation                                          
   |                                                                                                                    
   = note: `extract_backtrace` from trait: `fn(&std::error::Error + std::marker::Send + 'static) -> std::option::Option<
std::sync::Arc<error_chain::Backtrace>>`                                                                                
                                                                                                                        
error: aborting due to previous error                                                                                   
                                                                                                                        
error: Could not compile `dotenv`.                                                                                      
                                                                                                                        
To learn more, run the command again with --verbose.                                                                    
```

**Comment by Kerollmops** [comment]
I think this is not a resolves issue.
Can you please put a link to some solution to fix this compilation error or re-open this issue ?
